<a href="https://colab.research.google.com/github/ucfilho/Raianars_SelfTest_comp_02_July_2020/blob/master/JADE_stat_jul_03_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import time

In [2]:
!pip install PyFDE

In [3]:
import pyfde

In [4]:
# paper Self-adaptive differential evolution 01.pdf
# dim= 30, 50 and 100 based 
# f1 Sphere
# f2 Step 

In [5]:
!git clone https://github.com/ucfilho/Raianars_July_2020 #clonar do Github
%cd Raianars_July_2020

fatal: destination path 'Raianars_July_2020' already exists and is not an empty directory.
/content/Raianars_July_2020


In [6]:
import Function
import Go2MinMax

In [7]:
ITE=100 #10 # PONTOS quantas vezes vai alteral NPAR 
NPAR=100 # NUMBER OF PARTICLES
dim=3

fchoice='Schwefel_12'  #f2
Fun=Function.Schwefel_12
start_time = time.time() #INICIALIZA CONTAGEM DO TEMPO
MIN,MAX=Go2MinMax.Intervalo(dim,fchoice)
bounds = [(0,0)]*dim

for i in range(dim):
  bounds[i] = (MIN[i],MAX[i])

In [8]:
#print(bounds)

In [9]:

BEST_AGENTS=[]
RUNS=20
for i in range(RUNS):
  ANSWER_AGENTS=[]
  solver = pyfde.JADE(Fun, n_dim=dim, n_pop=NPAR, limits=bounds, minimize=True)
  solver.p = 0.05
  solver.c = 0.1
  solver.cr = 0.5
  solver.f = 0.5
  best, fit = solver.run(n_it=ITE)
  for x in best:
    ANSWER_AGENTS.append(x)
  ANSWER_AGENTS.append(fit)
  BEST_AGENTS.append(ANSWER_AGENTS)
BEST_AGENTS=np.array(BEST_AGENTS)
print(BEST_AGENTS)

[[ 1.34293471e-08 -7.97323802e-09 -1.06060089e-08 -2.36637958e-16]
 [-1.47798433e-08  2.08916466e-08 -1.76270932e-09 -2.74712526e-16]
 [-1.08068093e-08 -2.79262318e-09  2.97530063e-09 -4.14603868e-16]
 [ 2.57648253e-08 -4.77626571e-09 -2.23619897e-08 -1.10623217e-15]
 [-1.80420342e-09  3.82643602e-09 -6.75775189e-09 -2.97697176e-17]
 [ 3.84468609e-10  4.11666283e-09 -2.23065102e-08 -3.37439513e-16]
 [ 3.54836673e-09 -4.93718909e-09  1.32448485e-08 -1.55085089e-16]
 [ 3.80112731e-09 -3.40287046e-09 -5.50410526e-09 -4.06768653e-17]
 [ 7.84794398e-10  1.50575703e-08 -3.22006219e-08 -5.19189000e-16]
 [ 1.04827167e-08 -2.72012849e-09  9.64959921e-09 -4.73329393e-16]
 [-6.63859656e-09 -4.72918865e-09  4.30484586e-09 -2.23182617e-16]
 [-3.47090431e-08  1.28150216e-08  1.81568425e-08 -1.69803236e-15]
 [ 3.21643692e-08 -4.44558868e-08  3.81367563e-08 -1.85360441e-15]
 [ 8.77541840e-10  1.17387760e-08 -3.19428806e-09 -2.48716203e-16]
 [ 2.84545610e-09 -3.95423393e-09 -4.68269774e-09 -4.28671979e

In [10]:
TIME = (time.time() - start_time)/RUNS
BEST_AGENTS=np.array(BEST_AGENTS)
BEST_AGENTS_ST= BEST_AGENTS[BEST_AGENTS[:,-1].argsort()]
BEST=BEST_AGENTS_ST[0]
WORSE=BEST_AGENTS_ST[-1]
MEAN=np.mean(BEST_AGENTS,axis=0)
MAXFO=BEST_AGENTS[:,-1].max()
MINFO=BEST_AGENTS[:,-1].min()
STD=BEST_AGENTS[:,-1].std()

In [11]:
nome='JADE_Fo-'+str(0)+'_CRo-'+str(0)
print(nome,'NPAR',NPAR,'Iterações=',ITE,'Dim=',dim ,"Min/Max=",MIN[0],"/",MAX[0],'_',Fun.__name__)
print( '\n')
#print('BEST: ',BEST)
#print('MÉDIA: ',MEAN)
print('MÉDIA: ',MEAN[-1])
print('MIN __:',MINFO)
print('MAX__: ',MAXFO)
print('STD __:',STD)
print("Tempo Médio= %.3f segundos ---" % (TIME))
print(RUNS,'Rodadas') 
print()
print('BEST: ',BEST)

JADE_Fo-0_CRo-0 NPAR 100 Iterações= 100 Dim= 3 Min/Max= -100 / 100 _ Schwefel_12


MÉDIA:  -4.640983733436768e-16
MIN __: -1.853604410463703e-15
MAX__:  -2.976971755980746e-17
STD __: 4.99520627572188e-16
Tempo Médio= 0.041 segundos ---
20 Rodadas

BEST:  [ 3.21643692e-08 -4.44558868e-08  3.81367563e-08 -1.85360441e-15]


In [12]:
fit

-1.912129116018296e-16