<a href="https://colab.research.google.com/github/ucfilho/Raianars_SelfTest_comp_02_July_2020/blob/master/JADE_stat_jul_03_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import time

In [2]:
!pip install PyFDE

In [3]:
import pyfde

In [4]:
# paper Self-adaptive differential evolution 01.pdf
# dim= 30, 50 and 100 based 
# f1 Sphere
# f2 Step 

In [5]:
!git clone https://github.com/ucfilho/Raianars_July_2020 #clonar do Github
%cd Raianars_July_2020

fatal: destination path 'Raianars_July_2020' already exists and is not an empty directory.
/content/Raianars_July_2020


In [6]:
import Function
import Go2MinMax

In [7]:
ITE=100 #10 # PONTOS quantas vezes vai alteral NPAR 
NPAR=100 # NUMBER OF PARTICLES
dim=3

fchoice='Schwefel_12'  #f2
Fun=Function.Schwefel_12
start_time = time.time() #INICIALIZA CONTAGEM DO TEMPO
MIN,MAX=Go2MinMax.Intervalo(dim,fchoice)
bounds = [(0,0)]*dim

for i in range(dim):
  bounds[i] = (MIN[i],MAX[i])

In [8]:
#print(bounds)

In [9]:

solver = pyfde.JADE(Fun, n_dim=dim, n_pop=NPAR, limits=bounds, minimize=True)
solver.p = 0.05
solver.c = 0.1
best, fit = solver.run(n_it=ITE)

In [10]:
print("**Best solution found**")
print("x",best)
print("Fitness =",fit)

**Best solution found**
x [-1.67461710e-06 -4.68556568e-06  2.48763688e-05]
Fitness = -3.861054105723733e-10


In [11]:

BEST_AGENTS=[]
RUNS=20
for i in range(RUNS):
  ANSWER_AGENTS=[]
  solver = pyfde.JADE(Fun, n_dim=dim, n_pop=NPAR, limits=bounds, minimize=True)
  solver.p = 0.05
  solver.c = 0.1
  best, fit = solver.run(n_it=ITE)
  for x in best:
    ANSWER_AGENTS.append(x)
  ANSWER_AGENTS.append(fit)
  BEST_AGENTS.append(ANSWER_AGENTS)
BEST_AGENTS=np.array(BEST_AGENTS)
print(BEST_AGENTS)

[[ 8.19449896e-06 -5.92407622e-06  3.66611071e-06 -1.07547062e-10]
 [-1.81811567e-05  4.33794608e-05 -2.67118371e-05 -9.67799771e-10]
 [ 1.39713197e-05 -8.40226143e-06 -1.60193280e-05 -3.35420321e-10]
 [ 7.66494609e-06 -1.22681155e-05  9.60622310e-06 -1.04971113e-10]
 [-8.70221242e-06  2.32090759e-05  2.43841241e-05 -1.79868651e-09]
 [-2.70336732e-07  3.76354699e-05 -2.90510191e-05 -1.46535075e-09]
 [-3.40755561e-06 -7.23078422e-06  1.85502589e-05 -1.87384172e-10]
 [-4.13562482e-06  1.72718814e-05 -1.96585589e-05 -2.32205056e-10]
 [-1.61429040e-05  5.23672160e-06  8.89318191e-06 -3.83590337e-10]
 [ 7.17768628e-06 -2.29981671e-05  1.28132435e-05 -3.10850271e-10]
 [ 7.39569430e-06  4.68107304e-06 -2.17125939e-05 -2.93393756e-10]
 [ 1.14519736e-05 -5.11261999e-06 -9.89440122e-06 -1.83973467e-10]
 [ 5.89238296e-06 -1.02389565e-05  3.16702567e-06 -5.50042117e-11]
 [-3.11839449e-06  1.13338151e-05  9.23565300e-06 -3.81757491e-10]
 [-6.73785461e-07 -2.67822824e-06  5.75713777e-06 -1.74746045e

In [12]:
TIME = (time.time() - start_time)/RUNS
BEST_AGENTS=np.array(BEST_AGENTS)
BEST_AGENTS_ST= BEST_AGENTS[BEST_AGENTS[:,-1].argsort()]
BEST=BEST_AGENTS_ST[0]
WORSE=BEST_AGENTS_ST[-1]
MEAN=np.mean(BEST_AGENTS,axis=0)
MAXFO=BEST_AGENTS[:,-1].max()
MINFO=BEST_AGENTS[:,-1].min()
STD=BEST_AGENTS[:,-1].std()

In [13]:
nome='JADE_Fo-'+str(0)+'_CRo-'+str(0)
print(nome,'NPAR',NPAR,'Iterações=',ITE,'Dim=',dim ,"Min/Max=",MIN[0],"/",MAX[0],'_',Fun.__name__)
print( '\n')
#print('BEST: ',BEST)
#print('MÉDIA: ',MEAN)
print('MÉDIA: ',MEAN[-1])
print('MIN __:',MINFO)
print('MAX__: ',MAXFO)
print('STD __:',STD)
print("Tempo Médio= %.3f segundos ---" % (TIME))
print(RUNS,'Rodadas') 
print()
print('BEST: ',BEST)

JADE_Fo-0_CRo-0 NPAR 100 Iterações= 100 Dim= 3 Min/Max= -100 / 100 _ Schwefel_12


MÉDIA:  -4.2975141723447264e-10
MIN __: -1.7986865109968656e-09
MAX__:  -1.747460446581882e-11
STD __: 4.565702960390752e-10
Tempo Médio= 0.043 segundos ---
20 Rodadas

BEST:  [-8.70221242e-06  2.32090759e-05  2.43841241e-05 -1.79868651e-09]


In [14]:
fit

-6.634457968580622e-10